version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    tty: true
    links:
      - db
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: ./run.py
      FLASK_ENV: development
      PYTHONPATH: /src
    #command: poetry run flask run
  db:
    build: ./mysql/
    platform: linux/x86_64 #  M1 Mac の場合に必要　Windowsの場合は消す
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    environment:
      - MYSQL_ROOT_PASSWORD=hoge # パスワード設定（ローカル環境でしか使用しない）
      - TZ='Asia/Tokyo' # タイムゾーンを日本時間に設定
    ports:
      - 33306:3306 # ホストマシンのポート33306を、docker内のポート3306に接続する
